services:
  postgres:
    image: postgres:15
    container_name: birads_postgres
    environment:
      POSTGRES_DB: birads_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: birads_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app
    restart: unless-stopped

volumes:
  postgres_data: